name: tp_integration_mpf

description: "A new Flutter project."
publish_to: 'none'

version: 1.3.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

#  build_runner: ^2.4.6
#  mockito: ^5.4.4

flutter:
  uses-material-design: true